env:
  browser: true
  es6: true
  node: true
extends:
    - 'eslint:recommended'
    - 'prettier'
plugins:
    - 'prettier'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  prettier/prettier: 
    - error
  no-unused-vars: warn
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
